# Generated by Django 5.2.1 on 2025-05-09 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('sector', models.CharField(blank=True, max_length=100)),
                ('return1y', models.FloatField(blank=True, help_text='Rentabilidad en el último año', null=True)),
                ('fees', models.FloatField(blank=True, help_text='Comisiones anuales', null=True)),
                ('benchmark', models.CharField(blank=True, max_length=100)),
                ('volatility', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
